name: CI - Slef Hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Download model.h5
      run: wget --load-cookies ~/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies ~/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1cJiPA1XoCn-htXFEq7UYHb_Row3J3agf' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1cJiPA1XoCn-htXFEq7UYHb_Row3J3agf" -O model.h5 && rm -rf ~/cookies.txt

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tf:test

    - name: Run Docker Iamge (test)
      run: |
        docker run tf:test /bin/bash -c "python run.py test_input.png && ls"